# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoadSlopePluginII
                                 A QGIS plugin
 This plugin compute slope in percent for each line in the vector layer from DEM and split feature with more than two vertex into separate features by changing slope.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-16
        copyright            : (C) 2018 by Michaela Patakova
        email                : patakovamichala@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RoadSlopePluginII class from file RoadSlopePluginII.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .RoadSlopePluginII import RoadSlopePluginII
    return RoadSlopePluginII(iface)
